# ArgumentError: wrong number of arguments (1 for 2)
#   from (irb):1:in `calculate_product'
#   from (irb):4
#   from /Users/username/.rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'

# Two arguments were required, and instead one was given.

# From docs:
# "Raised when the arguments are wrong and there isn't a more 
# specific Exception class."
# Ref: https://ruby-doc.org/core-2.6.5/ArgumentError.html
